export const LISTS_LIST_REQUEST = "LISTS_LIST_REQUEST";
export const LISTS_LIST_SUCCESS = "LISTS_LIST_SUCCESS";
export const LISTS_LIST_FAIL = "LISTS_LIST_FAIL";

export const LISTS_CREATE_REQUEST = "LISTS_CREATE_REQUEST";
export const LISTS_CREATE_SUCCESS = "LISTS_CREATE_SUCCESS";
export const LISTS_CREATE_FAIL = "LISTS_CREATE_FAIL";

export const LISTS_UPDATE_REQUEST = "LISTS_UPDATE_REQUEST";
export const LISTS_UPDATE_SUCCESS = "LISTS_UPDATE_SUCCESS";
export const LISTS_UPDATE_FAIL = "LISTS_UPDATE_FAIL";


export const LISTS_DELETE_REQUEST = "LISTS_DELETE_REQUEST";
export const LISTS_DELETE_SUCCESS = "LISTS_DELETE_SUCCESS";
export const LISTS_DELETE_FAIL = "LISTS_DELETE_FAIL";